import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { readZipDirectory } from "./zipPreview";

// Generated by Python zipfile, including deflated data and a UTF-8 filename.
const fixture = Buffer.from("UEsDBBQAAAAIAIp2N10AAAAAAgAAAAAAAAAIAAAAcmVwb3J0cy8DAFBLAwQUAAAICACKdjddhqYQNgcAAAAFAAAAEgAAAHJlcG9ydHMv57WQ5p6cLnR4dMtIzcnJBwBQSwMEFAAAAAgAinY3XQAAAAACAAAAAAAAAAkAAABlbXB0eS50eHQDAFBLAQIUAxQAAAAIAIp2N10AAAAAAgAAAAAAAAAIAAAAAAAAAAAAEAD9QQAAAAByZXBvcnRzL1BLAQIUAxQAAAgIAIp2N12GphA2BwAAAAUAAAASAAAAAAAAAAAAAACAASgAAAByZXBvcnRzL+e1kOaenC50eHRQSwECFAMUAAAACACKdjddAAAAAAIAAAAAAAAACQAAAAAAAAAAAAAAgAFfAAAAZW1wdHkudHh0UEsFBgAAAAADAAMArQAAAIgAAAAAAA==", "base64");

async function withArchive(bytes: Buffer, run: (path: string) => Promise<void>) {
  const dir = await mkdtemp(join(tmpdir(), "threadex-zip-preview-"));
  try {
    const path = join(dir, "archive.zip");
    await writeFile(path, bytes);
    await run(path);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

test("lists nested UTF-8 files, directory markers and uncompressed sizes", async () => {
  await withArchive(fixture, async (path) => {
    assert.deepEqual(await readZipDirectory(path), [
      { path: "reports/", directory: true, size: 0, compressedSize: 2 },
      { path: "reports/結果.txt", directory: false, size: 5, compressedSize: 7 },
      { path: "empty.txt", directory: false, size: 0, compressedSize: 2 }
    ]);
  });
});

test("lists an empty ZIP", async () => {
  const bytes = Buffer.alloc(22);
  bytes.writeUInt32LE(0x06054b50);
  await withArchive(bytes, async (path) => assert.deepEqual(await readZipDirectory(path), []));
});

test("rejects truncated archives and invalid central directory bounds", async () => {
  await withArchive(fixture.subarray(0, -1), async (path) => {
    await assert.rejects(readZipDirectory(path), /could not be found/);
  });
  const bytes = Buffer.from(fixture);
  bytes.writeUInt32LE(0xfffffff0, bytes.length - 6);
  await withArchive(bytes, async (path) => {
    await assert.rejects(readZipDirectory(path), /bounds/);
  });
});

test("rejects ZIP64 and oversized directory counts before reading entries", async () => {
  for (const [count, message] of [[0xffff, /ZIP64/], [10_001, /too large/]] as const) {
    const bytes = Buffer.from(fixture);
    bytes.writeUInt16LE(count, bytes.length - 14);
    bytes.writeUInt16LE(count, bytes.length - 12);
    await withArchive(bytes, async (path) => {
      await assert.rejects(readZipDirectory(path), message);
    });
  }
});
