import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("manifest installs the automatic HTTP(S) page context content script", async () => {
  const manifest = JSON.parse(await readFile("extension/manifest.json", "utf8")) as { permissions?: string[]; content_scripts?: Array<{ matches?: string[]; js?: string[] }> };
  assert.ok(manifest.permissions?.includes("scripting"));
  assert.ok(manifest.permissions?.includes("cookies"));
  assert.ok(manifest.permissions?.includes("downloads"));
  assert.deepEqual(manifest.content_scripts, [{ matches: ["http://*/*", "https://*/*"], js: ["content.js"], run_at: "document_idle" }]);
  const content = await readFile("extension/content.js", "utf8");
  assert.match(content, /pageInjectionConfig/);
  assert.match(content, /browserContextReceiver/);
  assert.match(content, /injectBrowserContext/);
  assert.match(content, /data-local-browser-bridge-context-receiver/);
  assert.match(content, /Add to/);
  assert.match(content, /extension-context-key/);
  assert.doesNotMatch(content, /localStorage\./);
  assert.doesNotMatch(content, /extension-(?:page-snapshot|webp-screenshot)-key/);
  assert.match(content, /captureContextScreenshot/);
  assert.match(content, /function onPointerDown/);
  assert.match(content, /try\s*\{\s*contentGlobal\.__localBrowserBridgeContent\?\.dispose\(\);\s*\}\s*catch/);
  assert.match(content, /function dispose\(\)/);
  assert.match(content, /chrome\.runtime\.onMessage\.removeListener\(onExtensionMessage\)/);
  assert.match(content, /event\.shiftKey && event\.button === 2/);
  assert.match(content, /target\.right \+ gap/);
  assert.match(content, /function interceptMenuEvent/);
  assert.match(content, /Comment \(optional\)/);
  assert.match(content, /"user-comment": value/);
  assert.match(content, /createButton\("Copy"/);
  assert.doesNotMatch(content, /Copy to chat/);
  assert.match(content, /JSON\.stringify\(contextWithComment\(\)\)/);
  assert.doesNotMatch(content, /JSON\.stringify\(contextWithComment\(\), null, 2\)/);
  assert.match(content, /function showElementHighlight/);
  assert.match(content, /localBrowserBridgeHighlight/);
  assert.match(content, /host\.addEventListener\(eventName, interceptMenuEvent\)/);
  assert.match(content, /event\.stopImmediatePropagation\(\)/);
  assert.match(content, /\(\(\) => \{/);
  assert.doesNotMatch(content, /^export\s/m);
  const background = await readFile("extension/background.js", "utf8");
  assert.match(background, /listWindows/);
  assert.match(background, /listTargets/);
  assert.match(background, /chromeApi/);
  assert.match(background, /case "reactInspect"/);
  assert.match(background, /reactInspectExpression/);
  assert.match(background, /withReactComponents/);
  assert.match(background, /reactContextMetadata/);
  assert.match(background, /enrichPageContext/);
  assert.match(background, /chrome\.tabs\.captureVisibleTab/);
  assert.match(background, /contextScreenshotRetentionMs = 7 \* 24 \* 60 \* 60 \* 1_000/);
  assert.match(background, /convertToBlob\(\{ type: "image\/webp"/);
  assert.match(background, /getContextScreenshot/);
  assert.match(background, /storePageSnapshot/);
  assert.match(background, /getPageSnapshot/);
  assert.match(background, /pageSnapshotRetentionMs = 7 \* 24 \* 60 \* 60 \* 1_000/);
  assert.match(background, /chrome\.alarms\.create\(contextStorageCleanupAlarm/);
  assert.match(background, /indexedDB\.open\(contextStorageDatabaseName/);
  assert.match(background, /case "cdp"/);
  assert.match(background, /debuggerIdleTimeoutMs = 5_000/);
  assert.match(background, /chrome\.debugger\.detach/);
  assert.match(background, /scheduleDebuggerDetach\(tabId\)/);
  assert.match(background, /chrome\.debugger\.onDetach/);
  assert.match(background, /receiver: currentTabReceiver \?\? await findInjectionReceiver\(tabId\)/);
  assert.doesNotMatch(background, /enabled: false, tabId: tabId, mappings: \[\], receiver: null/);
  assert.doesNotMatch(background, /contextApiUrl/);
});

test("React inspection only reports component and source metadata", async () => {
  const source = await readFile("extension-src/reactInspect.ts", "utf8");
  assert.match(source, /__reactFiber\$/);
  assert.match(source, /_debugSource/);
  assert.match(source, /_debugStack/);
  assert.match(source, /elementSourceStack/);
  assert.match(source, /creationSource/);
  assert.doesNotMatch(source, /fetch\(/);
  assert.match(source, /sourceLocationAvailable/);
  assert.doesNotMatch(source, /memoizedProps/);
  assert.doesNotMatch(source, /memoizedState/);
});
